name: EKS Deploy
on:
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write
  statuses: write
  actions: read
  contents: read

jobs:
  call-vpc-workflow:
    uses: ./.github/workflows/deploy.yaml
    with:
      work-dir: "environments/eks_1"
      aws-region: "us-west-2"
    secrets:
      CI_ROLE: ${{ secrets.CI_ROLE }}